/**
 * The desktop agent ships two installers from one shared codebase, and the parts
 * of its configuration that have to agree live in files that cannot see each
 * other.
 *
 * `apps/child-desktop/{windows,macos}` are two Electron projects, each with its
 * own `package.json`, its own electron-builder block, and its own `build/`
 * directory of packaging resources. Neither holds any product behaviour — that
 * is all in `shared/` — so what can drift between them is exactly the things
 * nothing throws about:
 *
 *   - an application identifier that stops matching, so an upgrade installs
 *     alongside the old copy instead of over it
 *   - a library that moves on one platform only, which is a bug reproducible on
 *     one of the two machines in the house
 *   - a device type the agent reports that the API does not recognise, or that
 *     the parent's dashboard cannot offer — either of which produces a link code
 *     nothing can consume
 *   - a path agreed between a JavaScript module and a shell script or a plist,
 *     where the failure mode is a Mac that cannot resolve a name
 *
 * Read as text rather than imported wherever the file is not JSON, matching
 * familyBrandColors.test.js: this suite is CommonJS, and reaching into another
 * project's tooling to parse a plist would cost more than a regex.
 */
const fs = require('node:fs');
const path = require('node:path');

const REPO = path.join(__dirname, '../../..');
const read = (p) => fs.readFileSync(path.join(REPO, p), 'utf8');
const json = (p) => JSON.parse(read(p));

const DESKTOP = 'apps/child-desktop';
const windows = json(`${DESKTOP}/windows/package.json`);
const macos = json(`${DESKTOP}/macos/package.json`);
const shared = json(`${DESKTOP}/shared/package.json`);

describe('Child Desktop — the two platform projects agree', () => {
  const projects = [['windows', windows], ['macos', macos]];

  it('installs as one product on both platforms', () => {
    expect(windows.build.appId).toBe('ca.parentix.child-desktop');
    expect(macos.build.appId).toBe(windows.build.appId);
    expect(macos.build.productName).toBe(windows.build.productName);
  });

  it.each(projects)('%s links the shared package rather than copying it', (_name, project) => {
    expect(project.dependencies['@parentix/child-desktop-shared']).toBe('file:../shared');
  });

  /*
   * The agent runs inside whichever project launched it, so a library pinned
   * differently on the two sides is a difference in the shipping code with
   * nothing in `shared/` to show for it.
   */
  it('pins the same libraries on both platforms', () => {
    for (const library of ['axios', 'socket.io-client']) {
      expect(macos.dependencies[library]).toBe(windows.dependencies[library]);
    }
    expect(macos.devDependencies.electron).toBe(windows.devDependencies.electron);
    expect(macos.devDependencies['electron-builder']).toBe(windows.devDependencies['electron-builder']);
  });

  /*
   * `shared/` owns no dependencies — it declares them as peers so the copy in a
   * build is always the platform project's, the same rule the child app's shared
   * package follows. A real dependency here would put a second axios in one of
   * the two trees.
   */
  it('the shared package declares its libraries as peers only', () => {
    expect(shared.dependencies).toBeUndefined();
    for (const library of ['axios', 'socket.io-client']) {
      expect(shared.peerDependencies[library]).toBe(windows.dependencies[library]);
    }
  });

  /*
   * ESM everywhere except the preload, which Electron loads in a context with no
   * ESM loader — a `.js` preload inside a `"type": "module"` package fails to
   * load, and the window comes up with no bridge and no error worth reading.
   */
  it.each(projects)('%s is an ESM project', (_name, project) => {
    expect(project.type).toBe('module');
  });

  it('the preload keeps its .cjs extension', () => {
    expect(fs.existsSync(path.join(REPO, DESKTOP, 'shared/preload.cjs'))).toBe(true);
    expect(fs.existsSync(path.join(REPO, DESKTOP, 'shared/preload.js'))).toBe(false);
    expect(shared.exports['./preload.cjs']).toBe('./preload.cjs');
  });

  it.each(projects)('%s ships the packaging resources it names', (name, project) => {
    expect(fs.existsSync(path.join(REPO, DESKTOP, name, project.build.directories.buildResources))).toBe(true);
    // Generated by scripts/build-brand-assets.mjs; electron-builder converts it
    // to .ico and .icns at package time, so there is no committed icon in either
    // of those formats to check instead.
    expect(fs.existsSync(path.join(REPO, DESKTOP, name, 'build/icon.png'))).toBe(true);
    expect(fs.existsSync(path.join(REPO, DESKTOP, name, 'build/tray.png'))).toBe(true);
  });
});

describe('Child Desktop — the device types line up end to end', () => {
  const controller = read('services/api/src/controllers/deviceController.js');
  const childrenPage = read('apps/family-app/src/pages/Children.jsx');
  const agent = read(`${DESKTOP}/shared/src/services/agent.js`);

  const apiTypes = controller
    .match(/const DEVICE_TYPES = \[([^\]]+)\]/)[1]
    .match(/'([a-z]+)'/g)
    .map((quoted) => quoted.replace(/'/g, ''));

  const linkableTypes = childrenPage
    .match(/const DEVICE_TYPES = \[([\s\S]*?)\n\];/)[1]
    .match(/value: '([a-z]+)'/g)
    .map((match) => match.replace(/value: '|'/g, ''));

  it('the API knows about both desktop platforms', () => {
    expect(apiTypes).toEqual(expect.arrayContaining(['windows', 'mac']));
  });

  /*
   * The rule for the parent's list is that a client has to exist and be
   * installable, or choosing the type produces a link code nothing can consume
   * and a device row that stays "never connected" for ever with nothing to
   * explain why. Both desktop installers exist, so both belong on it.
   */
  it('a parent can generate a code for a computer', () => {
    expect(linkableTypes).toEqual(expect.arrayContaining(['windows', 'mac']));
  });

  it('every type the dashboard offers is one the API accepts', () => {
    for (const type of linkableTypes) expect(apiTypes).toContain(type);
  });

  /* The agent reports what it is running on as it links, and the API validates
     that against its own list before storing it. A value outside the list is
     silently ignored, so a drift here is a device that keeps the wrong icon. */
  it('the agent declares a type the API recognises', () => {
    const declared = agent.match(/type: p\.id === 'darwin' \? '(\w+)' : '(\w+)'/);
    expect(declared).not.toBeNull();
    expect(apiTypes).toContain(declared[1]);
    expect(apiTypes).toContain(declared[2]);
  });
});

describe('Child Desktop — macOS privileged helper', () => {
  const dnsModule = read(`${DESKTOP}/macos/src/platform/dns.js`);
  const plist = read(`${DESKTOP}/macos/build/launchd/ca.parentix.child-desktop.helper.plist`);
  const helper = read(`${DESKTOP}/macos/build/launchd/dns-helper.sh`);
  const postinstall = read(`${DESKTOP}/macos/build/pkg-scripts/postinstall`);

  /*
   * The agent writes a request file and launchd starts the helper on a change to
   * it. Three files have to name the same path, and if they stop agreeing the
   * only symptom is that website filtering silently never turns on.
   */
  it('the agent, the plist and the helper agree on the request path', () => {
    const requestPath = '/Users/Shared/Parentix/dns-request.json';
    expect(dnsModule).toContain("const SHARED = '/Users/Shared/Parentix'");
    expect(dnsModule).toContain("REQUEST = path.join(SHARED, 'dns-request.json')");
    expect(plist).toContain(`<string>${requestPath}</string>`);
    expect(helper).toContain('REQUEST="$SHARED/dns-request.json"');
  });

  it('the agent and the helper agree on the snapshot format', () => {
    expect(dnsModule).toContain("dns-snapshot.tsv");
    expect(helper).toContain('SNAPSHOT="$SHARED/dns-snapshot.tsv"');
  });

  /*
   * `/Users/Shared` is writable by every local account, so anything the helper
   * accepts, any user of the Mac can ask for as root. The protocol therefore
   * carries no addresses: the helper decides what "redirect" means. A future
   * edit that lets a request name a DNS server would be a local privilege
   * escalation shipped inside a parental control.
   */
  it('the helper accepts only redirect and restore, and no addresses', () => {
    const actions = [...helper.matchAll(/^\s{2}(\w+)\)$/gm)].map((match) => match[1]);
    expect(actions).toEqual(['redirect', 'restore']);
    expect(helper).not.toMatch(/sed[^\n]*"servers"/);
  });

  it('the plist launchd loads is the one the installer copies', () => {
    expect(postinstall).toContain('ca.parentix.child-desktop.helper.plist');
    expect(postinstall).toContain('/Library/LaunchDaemons/ca.parentix.child-desktop.helper.plist');
    expect(plist).toContain('<string>ca.parentix.child-desktop.helper</string>');
    // launchd silently refuses a daemon plist that a non-root account can write.
    expect(postinstall).toMatch(/chown root:wheel "\$PLIST"/);
    expect(postinstall).toMatch(/chmod 644 "\$PLIST"/);
  });

  /* The agent looks for the plist, not the script, when deciding whether
     website filtering can run: a helper on disk that launchd has not been told
     about will never run, and reporting the filter as available on that basis is
     the silent failure the whole `supported` idea exists to prevent. */
  it('the agent gates on the plist rather than the script', () => {
    expect(dnsModule).toContain("HELPER_PLIST = '/Library/LaunchDaemons/ca.parentix.child-desktop.helper.plist'");
    expect(dnsModule).toMatch(/fs\.access\(HELPER_PLIST\)/);
  });
});

describe('Child Desktop — the resolver cannot take a machine off the network', () => {
  const webFilter = read(`${DESKTOP}/shared/src/services/webFilter.js`);
  const winDns = read(`${DESKTOP}/windows/src/platform/dns.js`);

  /*
   * The single most dangerous thing this feature does. A machine whose resolver
   * points at 127.0.0.1 with nothing listening has no internet at all, and a
   * child cannot be expected to know that `netsh` exists.
   */
  it('the proxy is listening before the machine is pointed at it', () => {
    const proxyStarted = webFilter.indexOf('_state.port = await _proxy.start()');
    const dnsApplied = webFilter.indexOf('await p.dns.apply(');
    expect(proxyStarted).toBeGreaterThan(-1);
    expect(dnsApplied).toBeGreaterThan(proxyStarted);
  });

  it('a marker is written before the change, so a crash can be repaired', () => {
    const backupWritten = webFilter.indexOf(`writeJson(BACKUP_KEY`);
    const dnsApplied = webFilter.indexOf('await p.dns.apply(');
    expect(backupWritten).toBeGreaterThan(-1);
    expect(dnsApplied).toBeGreaterThan(backupWritten);
  });

  it('startup repairs before it applies', () => {
    expect(webFilter).toMatch(/export async function repairSystemDns/);
    const repair = webFilter.indexOf('await repairSystemDns();');
    const upstreams = webFilter.indexOf('await p.dns.upstreams()');
    expect(repair).toBeGreaterThan(-1);
    expect(upstreams).toBeGreaterThan(repair);
  });

  /* Windows records whether an interface took its DNS from DHCP, because
     `-ResetServerAddresses` is the right restore for one and silently wrong for
     the other — a household that set its own resolver would find it replaced by
     the ISP's, with nothing to connect the change to a parental control. */
  it('Windows records DHCP separately from a static resolver', () => {
    expect(winDns).toContain("dhcp  = ($ifc.Dhcp -eq 'Enabled')");
    expect(winDns).toContain('-ResetServerAddresses');
    expect(winDns).toContain('-ServerAddresses (');
  });
});
