import { Stack, StackProps, RemovalPolicy, Duration, CfnOutput } from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as elasticache from 'aws-cdk-lib/aws-elasticache';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';
import { ParentixConfig } from './config';

interface DataStackProps extends StackProps {
  config: ParentixConfig;
  vpc: ec2.Vpc;
}

/**
 * Stateful resources: Postgres, Redis, and the application secrets.
 *
 * Both data stores sit in isolated subnets and only accept traffic from the
 * security group the API tasks run in, which is created here so the ingress
 * rules can be written before the service exists.
 */
export class DataStack extends Stack {
  public readonly database: rds.DatabaseInstance;
  public readonly databaseSecret: secretsmanager.ISecret;
  public readonly appSecret: secretsmanager.Secret;
  public readonly redisEndpoint?: string;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    const { config, vpc } = props;
    const removalPolicy = config.retainDataOnDelete ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY;

    /**
     * Access is granted to the application subnets by CIDR rather than to the
     * API's security group.
     *
     * The security group belongs to the API stack, which already depends on
     * this one for the database endpoint; referencing it back here would make
     * the two stacks mutually dependent and undeployable. Those subnets hold
     * nothing but the Fargate tasks and have no route in from the internet, so
     * the CIDR is as tight in practice.
     */
    const applicationSubnets = vpc.selectSubnets({ subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS });

    // ── PostgreSQL ────────────────────────────────────────────────────────────
    const databaseSecurityGroup = new ec2.SecurityGroup(this, 'DatabaseSecurityGroup', {
      vpc,
      description: 'Parentix Postgres',
      allowAllOutbound: false,
    });

    applicationSubnets.subnets.forEach((subnet, index) => {
      databaseSecurityGroup.addIngressRule(
        ec2.Peer.ipv4(subnet.ipv4CidrBlock),
        ec2.Port.tcp(5432),
        `Application subnet ${index + 1}`
      );
    });

    this.database = new rds.DatabaseInstance(this, 'Database', {
      engine: rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_16_3 }),
      instanceType: config.database.instanceType,
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [databaseSecurityGroup],
      databaseName: 'parentix',
      // Rotatable credentials generated by AWS — never a value from this repo.
      credentials: rds.Credentials.fromGeneratedSecret('parentix', { secretName: `parentix/${config.envName}/db` }),
      allocatedStorage: config.database.allocatedStorageGb,
      maxAllocatedStorage: config.database.maxAllocatedStorageGb,
      storageEncrypted: true,
      multiAz: config.database.multiAz,
      backupRetention: Duration.days(config.database.backupRetentionDays),
      deleteAutomatedBackups: !config.retainDataOnDelete,
      deletionProtection: config.database.deletionProtection,
      removalPolicy,
      // Slow queries and connection errors land in CloudWatch instead of being
      // trapped inside the instance.
      cloudwatchLogsExports: ['postgresql'],
      enablePerformanceInsights: true,
      autoMinorVersionUpgrade: true,
    });

    this.databaseSecret = this.database.secret!;

    // ── Application secrets ───────────────────────────────────────────────────
    // JWT_SECRET is generated here so it never exists in source control.
    // FIELD_ENCRYPTION_KEY and the Stripe keys are placeholders: fill them in
    // once via the console or CLI. FIELD_ENCRYPTION_KEY in particular must never
    // be rotated after data exists — every encrypted column becomes unreadable.
    this.appSecret = new secretsmanager.Secret(this, 'AppSecret', {
      secretName: `parentix/${config.envName}/app`,
      description: 'Parentix API application secrets',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({
          FIELD_ENCRYPTION_KEY: '',
          STRIPE_SECRET_KEY: '',
          STRIPE_WEBHOOK_SECRET: '',
          STRIPE_PREMIUM_PRICE_ID: '',
          STRIPE_FAMILY_PRICE_ID: '',
        }),
        generateStringKey: 'JWT_SECRET',
        passwordLength: 64,
        excludePunctuation: true,
      },
      removalPolicy,
    });

    // ── Redis ─────────────────────────────────────────────────────────────────
    if (config.redis.enabled) {
      const redisSecurityGroup = new ec2.SecurityGroup(this, 'RedisSecurityGroup', {
        vpc,
        description: 'Parentix Redis (Socket.IO adapter)',
        allowAllOutbound: false,
      });
      applicationSubnets.subnets.forEach((subnet, index) => {
        redisSecurityGroup.addIngressRule(
          ec2.Peer.ipv4(subnet.ipv4CidrBlock),
          ec2.Port.tcp(6379),
          `Application subnet ${index + 1}`
        );
      });

      const subnetGroup = new elasticache.CfnSubnetGroup(this, 'RedisSubnetGroup', {
        description: 'Parentix Redis subnets',
        subnetIds: vpc.selectSubnets({ subnetType: ec2.SubnetType.PRIVATE_ISOLATED }).subnetIds,
      });

      const redis = new elasticache.CfnCacheCluster(this, 'Redis', {
        engine: 'redis',
        cacheNodeType: config.redis.nodeType,
        numCacheNodes: 1,
        cacheSubnetGroupName: subnetGroup.ref,
        vpcSecurityGroupIds: [redisSecurityGroup.securityGroupId],
        // Socket.IO fan-out is disposable state; losing it on restart is fine,
        // and skipping snapshots keeps the node small and cheap.
        snapshotRetentionLimit: 0,
      });
      redis.addDependency(subnetGroup);

      this.redisEndpoint = `redis://${redis.attrRedisEndpointAddress}:${redis.attrRedisEndpointPort}`;
      new CfnOutput(this, 'RedisEndpoint', { value: this.redisEndpoint });
    }

    new CfnOutput(this, 'DatabaseEndpoint', { value: this.database.dbInstanceEndpointAddress });
    new CfnOutput(this, 'DatabaseSecretArn', { value: this.databaseSecret.secretArn });
    new CfnOutput(this, 'AppSecretArn', { value: this.appSecret.secretArn });
  }
}
